apiVersion: v1
kind: Secret
metadata:
  name: example-secret
  namespace: default
type: Opaque
# This would be encrypted by SOPS in a real scenario
data:
  username: ZXhhbXBsZS11c2VybmFtZQ==  # example-username
  password: ZXhhbXBsZS1wYXNzd29yZA==  # example-password 