apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: example-sealed-secret
  namespace: default
spec:
  encryptedData:
    # This would be encrypted by kubeseal in a real scenario
    username: AgBy8hCF8...truncated...
    password: AgBy8hCF8...truncated...
  template:
    metadata:
      name: example-secret
      namespace: default
    type: Opaque 