apiVersion: apps/v1
kind: Deployment
metadata:
  name: troyops-app
spec:
  template:
    spec:
      containers:
      - name: app
        resources:
          limits:
            cpu: "1.0"
            memory: "1Gi"
          requests:
            cpu: "0.5"
            memory: "512Mi" 