apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

namespace: prod

commonLabels:
  environment: prod

patchesStrategicMerge:
  - deployment-patch.yaml
  - service-patch.yaml

replicas:
  - name: troyops-app
    count: 3 