apiVersion: apps/v1
kind: Deployment
metadata:
  name: troyops-app
spec:
  template:
    spec:
      containers:
      - name: app
        resources:
          limits:
            cpu: "0.2"
            memory: "256Mi"
          requests:
            cpu: "0.1"
            memory: "128Mi" 